const router = require("express").Router();
const productRoute = require("./product.route");
const accountAdminRouter = require("./account-admin.route");
const categoryRouter = require("./category.route");
const roleRouter = require("./role.route");
const designRouter = require("./design.route");
const clientRouter = require("./client.route");
const orderRouter = require("./order.route");
const wishlistStatsRouter = require("./wishlist-stats.route");
const collectionRouter = require("./collection.route");
const dashboardRouter = require("./dashboard.route");
const settingRouter = require("./setting.route");
const authMiddleware = require("../../../middlewares/admin/auth.middleware");
router.use("/account", accountAdminRouter);
router.use("/categories", authMiddleware.verifyToken, categoryRouter);
router.use("/products", authMiddleware.verifyToken, productRoute);
router.use("/collections", authMiddleware.verifyToken, collectionRouter);
router.use("/roles", authMiddleware.verifyToken, roleRouter);
router.use("/designs", authMiddleware.verifyToken, designRouter);
router.use("/clients", authMiddleware.verifyToken, clientRouter);
router.use("/order", authMiddleware.verifyToken, orderRouter);
router.use("/wishlists", authMiddleware.verifyToken, wishlistStatsRouter);
router.use("/dashboard", authMiddleware.verifyToken, dashboardRouter);
router.use("/settings", authMiddleware.verifyToken, settingRouter);
module.exports = router;
